using System.Collections.Generic;
using System.Linq;
using Content.Shared.Chat;
using Content.Shared.CCVar;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChannelFilterPopup : Popup
{
    // Starlight begin
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    // Starlight end
    // order in which the available channel filters show up when available
    private static readonly ChatChannel[] ChannelFilterOrder =
    {
        ChatChannel.Local,
        ChatChannel.Whisper,
        ChatChannel.Emotes,
        ChatChannel.Radio,
        ChatChannel.Notifications,
        ChatChannel.LOOC,
        ChatChannel.OOC,
        ChatChannel.Dead,
        ChatChannel.Admin,
        ChatChannel.AdminAlert,
        ChatChannel.AdminChat,
        ChatChannel.Server
    };

    private readonly Dictionary<ChatChannel, ChannelFilterCheckbox> _filterStates = new();

    public event Action<ChatChannel, bool>? OnChannelFilter;
    public event Action<string>? OnNewHighlights;

    public ChannelFilterPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HighlightButton.OnPressed += HighlightsEntered;
        // Add a placeholder text to the highlights TextEdit.
        HighlightEdit.Placeholder = new Rope.Leaf(Loc.GetString("hud-chatbox-highlights-placeholder"));

        // Load highlights if any were saved.
        string highlights = _cfg.GetCVar(CCVars.ChatHighlights); // Starlight

        if (!string.IsNullOrEmpty(highlights))
        {
            UpdateHighlights(highlights);
        }

        AutoFillCheckBox.Pressed = _cfg.GetCVar(CCVars.ChatAutoFillHighlights);
        AutoFillCheckBox.OnToggled += OnAutoFillToggled;
        _cfg.OnValueChanged(CCVars.ChatAutoFillHighlights, OnAutoFillCVarChanged);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _cfg.UnsubValueChanged(CCVars.ChatAutoFillHighlights, OnAutoFillCVarChanged);
    }

    public bool IsActive(ChatChannel channel)
    {
        return _filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed;
    }

    public void SetActive(ChatChannel channel, bool isActive)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed != isActive)
        {
            checkbox.Pressed = isActive;
            OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }

    public ChatChannel GetActive()
    {
        ChatChannel active = 0;

        foreach (var (key, value) in _filterStates)
        {
            if (value.IsHidden || !value.Pressed)
            {
                continue;
            }

            active |= key;
        }

        return active;
    }

    public void SetChannels(ChatChannel channels)
    {
        foreach (var channel in ChannelFilterOrder)
        {
            if (!_filterStates.TryGetValue(channel, out var checkbox))
            {
                checkbox = new ChannelFilterCheckbox(channel);
                _filterStates.Add(channel, checkbox);
                checkbox.OnPressed += CheckboxPressed;
                checkbox.Pressed = true;
            }

            if ((channels & channel) == 0)
            {
                if (checkbox.Parent == FilterVBox)
                {
                    FilterVBox.RemoveChild(checkbox);
                }
            }
            else if (checkbox.IsHidden)
            {
                FilterVBox.AddChild(checkbox);
            }
        }
    }

    public void UpdateHighlights(string highlights)
    {
        HighlightEdit.TextRope = new Rope.Leaf(highlights);
    }

    private void CheckboxPressed(ButtonEventArgs args)
    {
        var checkbox = (ChannelFilterCheckbox)args.Button;
        OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
    }

    private void HighlightsEntered(ButtonEventArgs _args)
    {
        OnNewHighlights?.Invoke(Rope.Collapse(HighlightEdit.TextRope));
    }

    // Starlight start
    /// <summary>
    ///     Event handler triggered when the auto-fill highlights checkbox is toggled.
    /// </summary>
    private void OnAutoFillToggled(ButtonToggledEventArgs args)
    {
        _cfg.SetCVar(CCVars.ChatAutoFillHighlights, args.Pressed);
        _cfg.SaveToFile();
    }

    /// <summary>
    ///     Event handler triggered when the auto-fill highlights CVar value changes.
    /// </summary>
    private void OnAutoFillCVarChanged(bool value)
    {
        AutoFillCheckBox.Pressed = value;
    }

    /// <summary>
    ///     Updates and renders the list of active auto-generated highlights in the UI.
    /// </summary>
    public void UpdateAutoHighlights(string autoHighlights)
    {
        if (string.IsNullOrEmpty(autoHighlights))
        {
            AutoHighlightsLabel.Visible = false;
            return;
        }

        var list = autoHighlights
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(h => h.TrimStart('@'))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(FormattedMessage.EscapeText)
            .Select(h => Loc.GetString("hud-chatbox-auto-highlights-bullet", ("item", h)));

        var bullets = string.Join("\n", list);
        var markup = Loc.GetString("hud-chatbox-auto-highlights-wrapper", ("bullets", bullets));

        AutoHighlightsLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(markup));
        AutoHighlightsLabel.Visible = true;
    }
    // Starlight end

    public void UpdateUnread(ChatChannel channel, int? unread)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox))
            checkbox.UpdateUnreadCount(unread);
    }
}
