- type: job
  id: NanoTrasenRepresentative
  name: job-name-ntrep
  jobSelectName: job-name-ntrep-job-select
  description: job-description-ntrep
  playTimeTracker: JobNanoTrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 30h # Still less than Magistrate. You should be experienced with Command before you tell them how to do their jobs.
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 8h
    - !type:TraitsRequirement
      traits:
        - Iterator
      inverted: true
  startingGear: CentralCommandRepresentativeGear
  icon: JobIconNanoTrasenRepresentative
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  displayWeight: 50
  access:
    - Cryogenics
    - Lawyer
    - Command
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Chemistry
    - Engineering
    - Research
    - Robotics
    - Detective
    - Salvage
    - Mining
    - SalvageLead
    - Security
    - Brig
    - Cargo
    - Mail
    - Atmospherics
    - Medical
    - IAA
    - Ntrep
    - Brigmedic
    - Surgery
    - Paramedic
    - Debrief
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: startingGear
  id: CentralCommandRepresentativeGear
  equipment:
    #shoes: ClothingShoesBootsLaceup
    #head: ClothingHeadHatCapNtrep
    id: NanoTrasenRepresentativePDA
    ears: ClothingHeadsetAltCCRep
    outerClothing: ClothingOuterCoatNtrep
    belt: BoxFolderCentComClipboard
  storage:
    back:
    - RubberStampNtrep
    - CaneNT
    - Flash

- type: chameleonOutfit
  id: NanoTrasenRepresentativeChameleonOutfit
  job: NanoTrasenRepresentative
  equipment:
    outerClothing: ClothingOuterCoatNtrep
