- type: Salaries
  id: standart
  jobs:
    Captain: 150
    HeadOfPersonnel: 130
    HeadOfSecurity: 140
    ChiefEngineer: 130
    ResearchDirector: 145
    ChiefMedicalOfficer: 130
    Quartermaster: 130

    BlueShield: 140
    NanoTrasenRepresentative: 140
    NanotrasenCareerTrainer: 140
    IAA: 76
    Magistrate: 170

    Chemist: 90
    Psychologist: 76
    Paramedic: 50
    MedicalDoctor: 58
    MedicalIntern: 23
    Surgeon: 90

    AtmosphericTechnician: 90
    StationEngineer: 54
    TechnicalAssistant: 23

    Warden: 90
    Detective: 80
    Brigmedic: 73
    DutyOfficer: 70
    SecurityOfficer: 64
    SecurityCadet: 23

    StationAi: 100
    Borg: 85

    Chaplain: 50
    Chef: 50
    Janitor: 30
    Botanist: 50
    Lawyer: 55
    Librarian: 50
    Musician: 40
    Bartender: 50
    Mime: 30
    Clown: 30
    ServiceWorker: 23
    Performer: 23
    Reporter: 46
    Assistant: 15
    Boxer: 23
    Zookeeper: 34

    Scientist: 65
    Roboticist: 58
    ResearchAssistant: 23

    SalvageLead: 75
    SalvageSpecialist: 60
    MiningSpecialist: 60
    CargoTechnician: 45
    MailTech: 55

    Visitor: 0
    Prisoner: 0
    StirStir: 0
