- type: department
  id: TSF
  name: department-TSF
  description: department-TSF
  color: "#22a7ff"
  roles:
  - SolGovOfficer
  - SolGovOfficerSheriff
  - TSFMCCrew
  - TSFMarine
  - TSFMarineElite
  editorHidden: true
